name: build_wheel
on:
  workflow_dispatch:

env:

jobs:
   build:
     runs-on: ubuntu-20.04
       defaults:
         run:
           working-directory: ${{github.workspace}}

       steps:
        - name: Create conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            auto-activate-base: false
            activate-environment: pytreedb
            environment-file: environment.yml
            use-only-tar-bz2: true

        - name: Install build package
          run: python -m pip install build

        - name: Build package
          run: python -m build

        - name: Save artifacts
          uses: actions/upload-artifact@v2
            with:
              name: Python wheels
              path: |
                ${{github.workspace}}/dist/*