repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.4.0
    hooks:
      - id: black_nbconvert

  - repo: https://github.com/s-weigand/flake8-nb

    rev: v0.5.3
    hooks:
      - id: flake8-nb

  - repo: https://github.com/pycqa/flake8
    rev: 7.4.1 
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 26.10.0
    hooks:
      - id: black
  
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.9.0
    hooks:
      - id: betterleaks
