repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.4.0
    hooks:
      - id: black_nbconvert

  - repo: https://github.com/s-weigand/flake8-nb

    rev: v0.3.1
    hooks:
      - id: flake8-nb