name: pytreedb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - pip
  - notebook
  - jupyter
  - numpy
  - pytest
  - flask
  - requests
  - python-dotenv
  - sphinx
  - myst-parser
  - sphinxcontrib-napoleon
  - pre-commit
  - pip:
    - pymongo[srv]
    - flake8
    - flake8-nb
    - black[jupyter]
    - black_nbconvert
