[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

# Testing commands for our wheels
test-command = "pytest {package}/pytreedb_server/test"
test-requires = ["pytest"]
