name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
      defaults:
        run:
          shell: bash -l {0}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: pytreedb
            environment-file: environment.yml
            python-version: 3.9
            auto-activate-base: false
        - name: Lint with flake8
          run: |
            conda activate pytreedb
            conda install -y flake8
            # stop the build if there are Python syntax errors or undefined names
            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            # run flake8nb
            python -m pip install flake8-nb
            python -m flake8_nb . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: MongoDB in GitHub Actions
          uses: supercharge/mongodb-github-action@1.7.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}
        - name: Test pytreedb with pytest
          env:
            CONN_URI: "mongodb://127.0.0.1:27017/"
            CONN_DB: "pytreedb"
            CONN_COL: "test"
          run: |
            conda activate pytreedb
            conda install -y pytest
            python -m pip install pytest-cov
            python -m pytest --cov pytreedb
        - name: Test pytreedb-server with pytest
          env:
            CONN_URI: "mongodb://127.0.0.1:27017/"
            CONN_DB: "pytreedb"
            CONN_COL: "test_server"
            FLASK_RUN: "1"
            FLASK_RUN_HOST: "127.0.0.1"
            FLASK_RUN_PORT: "12789"
            PYTREEDB_FILENAME: "pytree.db"
            PYTREEDB_DOWNLOAD: "https://github.com/3dgeo-heidelberg/pytreedb/raw/main/data/test/geojsons.zip"
          run: |
            python -m pytest webserver/pytreedb_server
        - name: Install dependencies (PyPi build)
          run: |
            conda activate pytreedb
            python -m pip install --upgrade pip
            pip install build
        - name: Build package (pytreedb)
          run: |
            conda activate pytreedb
            python -m build
        - name: Publish package
          uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
          with:
            user: __token__
            password: ${{ secrets.TESTPYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
            
          
        - name: Build package (pytreedb-server)
          working-directory: ./webserver
          run: |
            conda activate pytreedb
            python -m build
        - name: Publish package
          uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
          with:
            packages_dir: ./webserver/dist
            user: __token__
            password: ${{ secrets.TESTPYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
